[package]
name    = "nalgebra"
version = "0.18.1"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

description = "Linear algebra library with transformations and statically-sized or dynamically-sized matrices."
documentation = "https://nalgebra.org/rustdoc/nalgebra/index.html"
homepage = "https://nalgebra.org"
repository = "https://github.com/rustsim/nalgebra"
readme = "README.md"
categories = [ "science" ]
keywords = [ "linear", "algebra", "matrix", "vector", "math" ]
license = "BSD-3-Clause"
edition = "2018"

exclude = ["/ci/*", "/.travis.yml", "/Makefile"]

[lib]
name = "nalgebra"
path = "src/lib.rs"

[features]
default         = [ ]
std             = [ "alloc", "matrixmultiply", "rand/std", "alga/std", "rand_distr" ]
alloc = [ ]
arbitrary       = [ "quickcheck" ]
serde-serialize = [ "serde", "serde_derive", "num-complex/serde" ]
abomonation-serialize = [ "abomonation" ]
sparse = [ ]
debug = [ "approx/num-complex", "rand/std" ]
io = [ "pest", "pest_derive" ]

[dependencies]
typenum        = "1.10"
generic-array  = "0.12"
rand           = { version = "0.7", optional = true, default-features = false }
rand_distr     = { version = "0.2", optional = true }
num-traits     = { version = "0.2", default-features = false }
num-complex    = { version = "0.2", default-features = false }
num-rational   = { version = "0.2", default-features = false }
approx         = { version = "0.3", default-features = false }
alga           = { version = "0.9", default-features = false }
matrixmultiply = { version = "0.2", optional = true }
serde          = { version = "1.0", optional = true }
serde_derive   = { version = "1.0", optional = true }
abomonation    = { version = "0.7", optional = true }
mint           = { version = "0.5", optional = true }
quickcheck     = { version = "0.8", optional = true }
pest           = { version = "2.0", optional = true }
pest_derive    = { version = "2.0", optional = true }

#[patch.crates-io]
#alga = { git = "https://github.com/rustsim/alga", branch = "dev" }

[dev-dependencies]
serde_json = "1.0"
rand = { version = "0.7", features = ["small_rng"] }
# IsaacRng is used by benches; keep for reproducibility?
rand_isaac = "0.2"
### Uncomment this line before running benchmarks.
### We can't just let this uncommented because that would break
### compilation for #[no-std] because of the terrible Cargo bug
### https://github.com/rust-lang/cargo/issues/4866
#criterion = "0.2.10"

[workspace]
members = [ "nalgebra-lapack", "nalgebra-glm" ]

[[bench]]
name = "nalgebra_bench"
harness = false
path = "benches/lib.rs"

[profile.bench]
lto = true
